<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ATUIG88" failures="0" tests="10" name="runnerBDD.Runner" time="123.510" errors="1" timestamp="19 Nov 2021 16:40:54 GMT" skipped="0">
  <testcase classname="runnerBDD.Runner" name="runScenario" time="13.065"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="10.197">
    <error message="Step [enters the &lt;FullName&gt; &lt;Email&gt; &lt;Number&gt; &lt;Enquiry&gt; details] is defined with 4 parameters at &#039;stepDefinitionBDD.TC10.enters_the_full_name_email_number_enquiry_details(java.lang.String,java.lang.String,java.lang.String,java.lang.String)&#039;.
However, the gherkin step has 0 arguments.
Step text: enters the &lt;FullName&gt; &lt;Email&gt; &lt;Number&gt; &lt;Enquiry&gt; details" type="io.cucumber.core.exception.CucumberException">
      <![CDATA[io.cucumber.core.exception.CucumberException: Step [enters the <FullName> <Email> <Number> <Enquiry> details] is defined with 4 parameters at 'stepDefinitionBDD.TC10.enters_the_full_name_email_number_enquiry_details(java.lang.String,java.lang.String,java.lang.String,java.lang.String)'.
However, the gherkin step has 0 arguments.
Step text: enters the <FullName> <Email> <Number> <Enquiry> details
at io.cucumber.core.runner.PickleStepDefinitionMatch.arityMismatch(PickleStepDefinitionMatch.java:83)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:42)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:110)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:110)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runnerBDD.Runner" name="runScenario" time="10.152"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="13.553"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="9.847"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="19.037"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="13.973"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="14.381"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="9.195"/>
  <testcase classname="runnerBDD.Runner" name="runScenario" time="10.110"/>
</testsuite> <!-- runnerBDD.Runner -->
